import fs from 'fs';
import path from 'path';

const csvPath = path.resolve(process.cwd(), 'data/projects.csv');
const jsonPath = path.resolve(process.cwd(), 'data/projects.json');
const jsPath = path.resolve(process.cwd(), 'data/projects.js');

function parseCSVRow(row) {
  const result = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < row.length; i++) {
    const char = row[i];
    if (char === '"') {
      if (inQuotes && row[i + 1] === '"') {
        current += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (char === ',' && !inQuotes) {
      result.push(current.trim());
      current = '';
    } else {
      current += char;
    }
  }
  result.push(current.trim());
  return result;
}

function main() {
  const raw = fs.readFileSync(csvPath, 'utf8');
  const lines = raw.split(/\r?\n/).filter(Boolean);
  const header = lines.shift().split(',');

  const projects = lines.map(line => parseCSVRow(line)).filter(cells => cells.length > 1).map(cells => ({
    timestamp: cells[0] || '',
    title: cells[1] || '',
    abstract: cells[2] || '',
    status: cells[3] || '',
    submissionDate: cells[4] || '',
    targetJournal: cells[5] || '',
    priority: cells[6] || '',
    deadline: cells[7] || '',
    irbStatus: cells[8] || '',
    funding: cells[9] || '',
    docsLink: cells[10] || '',
    coauthors: cells[11] || '',
    keywords: cells[12] || '',
    lastActivity: cells[13] || ''
  }));

  const payload = { updated: new Date().toISOString(), count: projects.length, projects };
  fs.writeFileSync(jsonPath, JSON.stringify(payload, null, 2));
  const js = `// Auto-generated by scripts/build_data.mjs\nwindow.__PROJECTS__ = ${JSON.stringify(payload)};`;
  fs.writeFileSync(jsPath, js);
  console.log(`Wrote ${projects.length} projects to ${path.relative(process.cwd(), jsonPath)} and ${path.relative(process.cwd(), jsPath)}`);
}

main();
